Add caliper to saxpy
LLNL/benchpark pull request #112
Opened 2024-01-14 23:55 UTC by rfhaque

2024-01-15 17:10 UTC, pearce8 approved these changes

2024-01-15 21:02 UTC, pearce8 requested changes
Why is the CI run failing?

2024-01-15 23:03 UTC, rfhaque commented
> Why is the CI run failing?

@pearce8 Fixed. The license comments had a # instead of forward slashes.

2024-01-16 00:44 UTC, pearce8 approved these changes

2024-01-16 00:44 UTC, merged

2024-01-16 19:11 UTC, daboehme commented on repo/saxpy/saxpy.cc
> +      adiak_clustername();
Let's just use `adiak_collect_all()` for these

2024-01-16 19:11 UTC, daboehme commented on repo/saxpy/saxpy.cc
> +      CALI_MARK_BEGIN("problem");
I think the `problem` region is redundant since it's essentially the same as `main`