Config for JUWELS Booster (JSC)
LLNL/benchpark pull request #160
Opened 2024-03-06 10:10 UTC by caropen

2024-03-06 10:13 UTC, caropen commented on configs/JSC-JUWELS-Booster-rome-A100-Infiniband/system_definition.yaml
> +    vendor: tba
@AndiH, can you fill this?

2024-03-06 10:14 UTC, caropen commented
@AndiH @jayeshbadwaik (from Jülich) please also check

2024-03-06 11:13 UTC, AndiH reviewed
Added my parts! The filename contains `rome`, should it – maybe – be `zen2`?

2024-03-06 11:13 UTC, AndiH commented on configs/JSC-JUWELS-Booster-rome-A100-Infiniband/system_definition.yaml
> +    vendor: tba
```suggestion
    vendor: Atos
```

2024-03-06 11:13 UTC, AndiH commented on configs/JSC-JUWELS-Booster-rome-A100-Infiniband/system_definition.yaml
> +    name: tba
```suggestion
    name: XH2000
```

2024-03-06 15:15 UTC, SebastianAchilles requested changes

2024-03-06 15:15 UTC, SebastianAchilles commented on configs/JSC-JUWELS-Booster-rome-A100-Infiniband/auxiliary_software_files/compilers.yaml
> +      operating_system: rocky9
```suggestion
      operating_system: rocky8
```

JUWELS Booster is using Rocky 8, c.f. 

```
[jwlogin21 ~]$ cat /etc/os-release | grep PRETTY_NAME
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
```

2024-03-06 15:15 UTC, SebastianAchilles commented on configs/JSC-JUWELS-Booster-rome-A100-Infiniband/auxiliary_software_files/compilers.yaml
> +      target: aarch64
```suggestion
      target: x86_64
```

JUWELS Bosoter is using AMD Zen2 which are x86_64.

2024-06-20 15:25 UTC, pearce8 approved these changes

2024-06-20 15:55 UTC, merged