[draft] Testing Salmon/Openmp
LLNL/benchpark pull request #391
Opened 2024-10-07 18:32 UTC by dyokelson

2025-01-17 23:11 UTC, pearce8 requested changes

2025-01-17 23:11 UTC, pearce8 commented on .github/workflows/run.yml
@slabasan does it work on dynamic systems?  Can you add a dynamic system dry run?

2025-01-21 18:24 UTC, slabasan commented on .github/workflows/run.yml
Added it now along with the `application.py`. Need to confirm it's correct through github CI.

2025-02-18 16:35 UTC, slabasan commented
Moved feature branch to upstream, replaced by #619

2025-02-18 16:35 UTC, closed without merging