Adding Sandia microbenchmarks experiment class
LLNL/benchpark pull request #431
Opened 2024-11-13 18:50 UTC by august-knox

Adding sandia microbenchmarks experiment class. Workloads include mpi_overhead and msgrate.

Potentially closes #323 
Replaces #381

2024-11-15 00:53 UTC, pearce8 requested changes
@august-knox Fix failing CI tests

2024-11-15 22:32 UTC, pearce8 approved these changes

2024-12-16 20:18 UTC, nhanford approved these changes
This alll looks good and works correctly on Dane. Thanks!

2024-12-17 00:58 UTC, pearce8 approved these changes

2024-12-17 00:58 UTC, merged