features/branson
LLNL/benchpark pull request #462
Opened 2024-12-01 04:32 UTC by rfhaque

2024-12-01 04:34 UTC, rfhaque commented on repo/branson/package.py
> +        args.append(f"-DBUILD_TESTING=OFF")
@pearce8 This is just a temporary fix for lasssen. Need to work with the branson team to fix build issues on that system.

2024-12-02 20:40 UTC, pearce8 requested changes
Please add a dry run.

2024-12-09 19:14 UTC, alexrlongne commented on repo/branson/package.py
> +        args.append(f"-DBUILD_TESTING=OFF")
I'll look at the RNG package again and see if an update fixes this.

2025-02-20 04:27 UTC, pearce8 commented
@rfhaque Please update:  which machines does the code work on?  What are the outstanding items to fix?

2025-02-20 18:45 UTC, rfhaque commented
> @rfhaque Please update: which machines does the code work on? What are the outstanding items to fix?

The code works on all the LC systems (ruby, lassen, tioga) and on the LANL venado system. Once the cmake changes are upstreamed to the branson repo, we can merge this PR

2025-05-26 14:43 UTC, pearce8 requested changes
@rfhaque Do you still want to merge this?  If so, please update.

2025-09-10 23:22 UTC, scheibelp reviewed
minor compatibility issue w/ #953 (should be resolved w/ merge from develop)

2025-09-10 23:22 UTC, scheibelp commented on repo/branson/package.py
>  from spack.pkg.builtin.boost import Boost
Referring to upstream packages changed in #953, but I think since `branson` was in the repo for that, you will get the appropriate update if merging develop into this.

2025-09-29 20:00 UTC, slabasan commented
@scheibelp `NotImplementedError: "branson" cannot run with MPI only without inheriting from MpiOnlyExperiment. Choose from ['rocm', 'cuda', 'openmp']`

2025-09-30 00:22 UTC, scheibelp approved these changes, later dismissed
I think this was just missing the `MpiOnlyExperiment` logic added in https://github.com/LLNL/benchpark/commit/ce3ffb6ba06bc50cbd8201c191250f56f8708b74#diff-9607e034d65374d4f8618d80af3e2d5033d973bdf09932cb07b5981232425232 - all the dry runs pass now.

I think someone other than me has to approve because I submitted the latest commits to this PR @slabasan, but I am adding an approving review to say the other parts look good to me.

2025-09-30 02:27 UTC, rfhaque commented
@scheibelp Doees sparta need to provide an `mpi` variant for this to work? mpi is always on in sparta and thus a variant is not needed

2025-09-30 03:56 UTC, scheibelp commented
It appears to be necessary based on the logic added by ce3ffb6ba0 but @michaelmckinsey1 am I missing a way for a package that always uses mpi to avoid this?

2025-09-30 17:14 UTC, michaelmckinsey1 commented
> It appears to be necessary based on the logic added by [ce3ffb6](https://github.com/LLNL/benchpark/commit/ce3ffb6ba06bc50cbd8201c191250f56f8708b74) but @michaelmckinsey1 am I missing a way for a package that always uses mpi to avoid this?

@scheibelp All programming models run with MPI, but to run only with MPI the experiment must inherit from `MpiOnlyExperiment`. This is to differentiate between experiments that cannot be ran only with MPI `experiment+mpi`, such as `babelstream+mpi`. This is a small set of cases.

2025-09-30 18:16 UTC, scheibelp commented
I think what @rfhaque is saying is that it would never make sense to `experiment init branson ~mpi`, so the presence of an `mpi` variant is confusing.

@michaelmckinsey1 I think that means that if an `experiment init branson` would fail based on the logic in https://github.com/LLNL/benchpark/blob/develop/lib/benchpark/experiment.py#L279 (it wants mpi to be mentioned explicitly).

I was thinking perhaps https://github.com/LLNL/benchpark/blob/develop/.github/utils/dryruns.py was dispatching the wrong call, but it seems like it was generating the appropriate `experiment init branson` for [e830b9d](https://github.com/LLNL/benchpark/pull/462/commits/e830b9d64460443461bc813d51079d009403b95b), but that it was rejected by the logic in `experiment.py`.

Is it your opinion such experiments should have an `mpi` variant? Or am I missing a way for an experiment to be set up this way?

2025-09-30 19:07 UTC, michaelmckinsey1 commented
The `mpi` variant is true by default, so that is why `experiment init branson` specs to `branson+mpi` without needing to explicitly write `+mpi`. I think it makes sense to have an explicit `mpi` variant because of the babelstream example. I don't see the test where the logic is failing, but I can take a look if it is.

2025-09-30 19:54 UTC, slabasan approved these changes, later dismissed
LGTM, but waiting on the package.py to be updated upstream?

2025-10-03 22:25 UTC, michaelmckinsey1 commented
This PR raised some confusion about the `MpiOnlyExperiment` mechanism. It is described https://github.com/LLNL/benchpark/pull/904 and in the docs for writing an experiment. It should be generally included for every experiment, except cases like `babelstream`, which can not be ran for `babelstream+mpi`, but can be ran for `babelstream+mpi+cuda`. So it is used to indicate whether running `+mpi` without any programming models is valid.

Inheriting from `MpiOnlyExperiment` is used to check spec validity https://github.com/LLNL/benchpark/blob/dd1b469c84f23ad1bd334762a145cb0cb7b416a0/lib/benchpark/experiment.py#L259-L296. https://github.com/LLNL/benchpark/pull/931 may drive some changes to `MpiOnlyExperiment`.

2025-12-24 20:01 UTC, pearce8 approved these changes

2026-01-05 14:20 UTC, merged