Feature/gromacs
LLNL/benchpark pull request #476
Opened 2024-12-08 03:46 UTC by rfhaque

Convert gromacs to experiment.py
- Tested on ruby(openmp), lassen(openmp, cuda), tioga(openmp, rocm)
- Does NOT work on rzvernal (spack concretizer error)
- All external blas/lapack libs available on lassen (cusolver, cublass, essl etc) do not append an underscore in the symbol names. This results in a linker error in gromacs. All attempts to build a blas library like openblas were unsuccessful. Hence, we default to using gromacs' internal blas/lapack implementation on lassen (ppc64le)
- Using rocblas/rocsolver for blas/lapack on tioga results in a segfault for the rocm experiment (intel mkl library works)
- The mapping of cores, gpus to ranks is not well-understood. Additional performance optimizations need to be investigated
- Bonded interactions do not work on the GPU (its possible the input file used for testing does not have any GPU interactions)
- Added a variant for GPU-aware MPI (off: disable, on: enable, but allow spack to ignore, force: force spack to use GPU-aware MPI, but may result in error if not supported by the MPI implementation)
- CUDA variant does not work for v2024 (only works for v2023.3)
- Enabling GPU-aware MPI requires setting the CXX_EXE_LINKER_FLAGS in gromacs. Directly setting CXX_EXE_LINKER_FLAGS breaks the CUDA build on lassen
- May not work on static legacy systems
- Variants have been added to the system init scripts to select between different blas/lapack libraries available on the sytem

Building the code in benchpark:
Initializing systems:
tioga:
bin/benchpark system init --dest=tioga-mkl llnl-elcapitan rocm=551 compiler=cce +gtl lapack=intel-oneapi-mkl blas=intel-oneapi-mkl
bin/benchpark system init --dest=tioga-rocm llnl-elcapitan rocm=551 compiler=cce +gtl lapack=rocsolver blas=rocblas

ruby:
bin/benchpark system init --dest=ruby-mkl llnl-cluster compiler=gcc lapack=intel-oneapi-mkl blas=intel-oneapi-mkl

lassen:
bin/benchpark system init --dest=lassen-cusolver llnl-sierra cuda=11-8-0 compiler=clang-ibm lapack=cusolver blas=cublas

Creating gromacs experiment:
rocm:
bin/benchpark experiment init --dest ./gromacs-rocm gromacs +openmp+rocm~cuda gpu-aware-mpi=force

openmp:
bin/benchpark experiment init --dest ./gromacs-openmp gromacs +openmp~cuda~rocm gpu-aware-mpi=off

cuda:
bin/benchpark experiment init --dest ./gromacs-cuda gromacs version=2023.3 +openmp+cuda~rocm gpu-aware-mpi=on

Benchpark setup:
tioga(rocm, openmp)
bin/benchpark setup gromacs-rocm tioga-mkl <work_dir> - works
bin/benchpark setup gromacs-rocm tioga-rocs <work_dir> - segfaults
bin/benchpark setup gromacs-openmp tioga-mkl <work_dir> - works
bin/benchpark setup gromacs-openmp tioga-rocs <work_dir> - works

ruby(openmp)
bin/benchpark gromacs-openmp ruby-mkl <work_dir> - works
bin/benchpark gromacs-openmp ruby-openblas <work_dir> - works

lassen(cuda, openmp)
bin/benchpark gromacs-cuda lassen-cusolver <work_dir> - works
bin/benchpark gromacs-openmp lassen-cusolver <work_dir> - works, but performance is poor

2024-12-09 21:18 UTC, pearce8 requested changes
- [x] update to current develop to use on el capitan
- [x] add dry runs for what works
- [x] create an issue with outstanding questions for Peter (concretization etc.)
- [x] create an issue with outstanding questions for Szilard

2024-12-13 23:50 UTC, rfhaque commented
@pearce8 This is ready to merge

2024-12-14 16:56 UTC, pearce8 approved these changes

2024-12-14 17:28 UTC, pearce8 approved these changes

2024-12-15 02:56 UTC, merged