Add HPCC mpi-only to benchpark
LLNL/benchpark pull request #76
Opened 2023-12-16 03:36 UTC by rfhaque

Tested on cts1

2023-12-18 23:27 UTC, pearce8 commented
@rfhaque Please test on its-1 using the x86 config.

2023-12-18 23:31 UTC, pearce8 requested changes

2023-12-18 23:31 UTC, pearce8 commented on configs/cts1/auxiliary_software_files/packages.yaml
Please remove fftw as a handle expected from a system.  We should use Spack to build it instead.

2023-12-18 23:31 UTC, pearce8 commented on experiments/hpcc/mpi-only/ramble.yaml
environments:
       hpcc:
         packages:


Should not have fftw.

2023-12-19 01:44 UTC, rfhaque commented on configs/cts1/auxiliary_software_files/packages.yaml
@pearce8 Removed fftw

2023-12-19 01:45 UTC, rfhaque commented
> @rfhaque Please test on its-1 using the x86 config.

Tested on cts1 with the x86 config

2023-12-19 01:55 UTC, pearce8 approved these changes

2023-12-19 01:56 UTC, merged