Removing magic
LLNL/benchpark pull request #79
Opened 2023-12-18 22:23 UTC by pearce8

Removing references to site-specific compiler wrappers.

2023-12-18 22:24 UTC, pearce8 commented
@rfhaque Please test all relevant benchmarks on the updated systems.

2023-12-18 22:32 UTC, pearce8 commented on configs/ats4/auxiliary_software_files/packages.yaml
Do we need this to be defined?  If yes, is there a non-tce version?

 git-lfs:
    externals:
    - spec: git-lfs@2.11.0
      prefix: /usr/tce

2023-12-18 22:37 UTC, pearce8 commented on configs/ats2/variables.yaml
@rfhaque Is there a non-tce location for lrun?  We are currently finding it in /usr/tcetmp/bin/lrun.

2023-12-21 21:39 UTC, becker33 reviewed
Looks good to me, commenting instead of approving because @rfhaque is doing manual testing.

2023-12-21 21:39 UTC, becker33 commented on configs/ats4/auxiliary_software_files/packages.yaml
> -      prefix: /usr/tce
This change seems orthogonal?

2023-12-22 02:14 UTC, pearce8 commented on configs/ats4/auxiliary_software_files/packages.yaml
> -      prefix: /usr/tce
yes, undoing.

2023-12-23 21:39 UTC, rfhaque requested changes
@pearce8 @scheibelp @becker33 Tested with the spack commit #8371bb4e. The following benchmarks have been tested
1. amg2023 (openmp/cts1, openmp/x86, openmp/ats2, openmp/ats4, rocm/ats4, cuda/ats2)
2. saxpy (openmp/ats4, rocm/ats4)
3. raja-perf (openmp/ats4, mpi-only/ats4, rocm/ats4)

2023-12-23 21:39 UTC, rfhaque commented on configs/ats4/auxiliary_software_files/compilers.yaml
> +      fc:  /opt/cray/pe/cce/16.0.0/bin/crayftn
@pearce8 amg2023 fails with the native cray compiler. It depends on workarounds in the magic wrapper

2023-12-28 22:40 UTC, pearce8 commented
AMG fails on tioga:

    configure: error: linking to Fortran libraries from C fails

Moving work on this to a separate PR#89.

2023-12-28 22:40 UTC, merged