Feature caliper modifier saxpy
LLNL/benchpark pull request #90
Opened 2023-12-28 22:49 UTC by rfhaque

@pearce8 caliper modifier for saxpy. Tested on topdown and cuda modes on quartz and lassen respectively

2023-12-28 23:36 UTC, pearce8 requested changes
We need to work towards not requiring libunwind.  This may be a Caliper package change - or a change to how we indicate to build Caliper.

2024-01-02 17:29 UTC, daboehme commented
> We need to work towards not requiring libunwind. This may be a Caliper package change - or a change to how we indicate to build Caliper.

Hi @rfhaque - you can either turn off the libunwind option in the Caliper spack spec to build without libunwind, or point spack to the system install of libunwind on Lassen.

2024-01-02 23:30 UTC, daboehme reviewed
Added a few comments in the code. Otherwise looks OK to me.

2024-01-02 23:30 UTC, daboehme commented on repo/saxpy/saxpy.cc
> +      adiak_clustername();
If you're using Adiak v0.4.0+ you can use `adiak_collect_all()` to get all the Adiak built-in metadata

2024-01-02 23:30 UTC, daboehme commented on repo/saxpy/saxpy.cc
> +      CALI_MARK_END("problem");
I guess you can merge this `#ifdef` block into the next. Also looks like `problem` is essentially the same region as `main` so it might be redundant.

2024-01-17 02:50 UTC, closed without merging